### ISSUE TITLE
Homework - Sidebar

### ISSUE THREAD

**Issue by Daniil-Mudrak** [Veronika573/Educayion#1]
1. Please remove unnecessary space before the button tag. https://github.com/Veronika573/Educayion/blob/9809731af4047975967540c105ef245974234610/sadebar/index.html#L17
You can use `Ctrl+Shift+I` to format your code.

2. Use another class name for sidebar active state, not 'rotate' because your sidebar don't rotate on it active state, it slides right.
https://github.com/Veronika573/Educayion/blob/9809731af4047975967540c105ef245974234610/sadebar/main.js#L5

3. Please use semicolon here or remove these at all. You should choose one code style which you like.
https://github.com/Veronika573/Educayion/blob/9809731af4047975967540c105ef245974234610/sadebar/main.js#L6

4. It is unnecessary line of the code
https://github.com/Veronika573/Educayion/blob/9809731af4047975967540c105ef245974234610/sadebar/style.css#L9

**Comment by NaincyKumariKnoldus** [comment]
Hey @Daniel-developer5 Can I do this please? I would have love to do this.
